### ISSUE TITLE
@Import(ResultBeanResponseProcessor.class)似乎不起作用

### ISSUE THREAD

**Issue by JeremeLau** [dadiyang/http-api-invoker#12]
我有一个形如 
`{
    "code": 200,
    "data": object,
    "msg": null
}`
的返回结果，在结合Spring的时候，使用`@Import(ResultBeanResponseProcessor.class)`，但是结果好像不如预期
`can not cast to int, value : {"code":200,"data":1}`

**Comment by dadiyang** [comment]
你使用的接口代理对象是Spring托管的吗？
可以打个断点调试一下吗？

**Comment by JeremeLau** [comment]
是我自己的原因，已经修正
