### ISSUE TITLE
其实rpc的原理貌似也类似

### ISSUE THREAD

**Issue by kaitezhan** [dadiyang/http-api-invoker#2]

**Comment by dadiyang** [comment]
是的。RPC有一个客户端，整合比较方便，但是跨平台能力比较差些。HTTP接口则比较自由，任何语言都可以支持，但是需要调用方自己写客户端。
通过提供 HTTP 接口，再使用这个 invoker 框架快速创建客户端包，供 java 语言调用。然后如果不想依赖客户端包或者使用其他语言写的程序需要调用，可以自己发请求。

**Comment by kaitezhan** [comment]
感谢回复，还有个问题想请教下。我在spring环境测试的时候,注入的返回类型是ResponseProcessor；然后我写了个方法返回类型是ResultBean<City>,为什么这种会不做处理？

**Comment by dadiyang** [comment]
返回类型是ResponseProcessor？
可以贴一下关键代码我看一下吗？

**Comment by dadiyang** [comment]
你使用的是 ResultBeanResponseProcessor 吗？这个实现的功能是将后台返回的成功 {"code": 0,"data": 123} 或者失败 {"code": -1,"msg": "出错啦~"} 这样的响应信息进行解晰，然后如果是成功，则将响应体中的 data 进行反序列化后返回，如果出错，则把 msg 中的内容做为异常信息抛出异常。

如果你的返回值本身就是一个 ResultBean，即包含了 code/data/msg，那么我们认为你想自己解析结果，所以会忽略，直接反序列化整个响应体。

因为整合 Spring 的时候，注册的 ResultBeanResponseProcessor 是全局的，但是可以会出现某些特殊接口，例如某些不规范的翻页接口返回这样的响应 {"code": 0, "data": [...],"total": 1000,"pageIndex": 1,"pageSize": 10}，这时候自动解析只能拿到data 里面的数据，但是可能你同时需要翻页信息，这种情况下，我们不希望框架来自动解析，利用这个特性，我们可以让这种特殊的接口绕过自动解析。
