### ISSUE TITLE
想问一下，和spring的resttemplate有啥区别么？在功能上。

### ISSUE THREAD

**Issue by spyman1802** [dadiyang/http-api-invoker#3]

**Comment by dadiyang** [comment]
实现的功能可以说是一样的。要说区别，就像 Spring 的 JDBCTemplate 和 MyBatis 的区别一样。前者是对直接使用 JDBC 的操作的简化，而后者则是将 SQL 语句与 interface 绑定，直接屏蔽了 JDBC 底层所有细节，无需手写实现类，直接使用接口的动态代理来访问数据库。

发送 HTTP 请求也是这样，我们当然可以使用 RestTemplate 或者直接使用 HttpClient 这些工具发送请求，但是每次调用 http 请求的时候都必须直接与 http 接口的细节打交道。而使用 http-api-invoker 框架，你只需要创建 interface 然后将 url 通过注解绑定在接口方法上，即可直接使用生成的动态代理来发送 HTTP 请求，屏蔽了发送请求的细节。

另外，若同一个接口有多处调用，则后续的调用者只需要像调用一个普通方法一样调用动态代理的相应方法即可，无需要再与 url 等打交道。若使用 RestTemplate，则要么我们需要额外封装一个方法，要么每次调用都拷贝一份发送请求的代码。
