### ISSUE TITLE
感觉调用方式上很像是SpringCloud的Feign

### ISSUE THREAD

**Issue by Eagle-Strike** [dadiyang/http-api-invoker#4]

**Comment by dadiyang** [comment]
是的。可以认为是轻量级的Feign。

**Comment by dadiyang** [comment]
这个框架非常小，只有 72K。
具有Feign那样的接口调用方式，还提供了 **ResultBean 自动解析、Mock等功能，最低支持JDK6**，既可以整合Spring，也可以单独使用。
扩展性方面，可以个性化定制请求发送过程中的各个生命周期。
做这个的初衷是给不在 SpringCloud 体系中的项目提供一个**轻量级的、可以快速上手的http接口调用框架**。
